# Generated by Django 2.0.7 on 2018-07-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50, verbose_name='项目名')),
                ('pro_href', models.URLField(verbose_name='代码下载地址')),
                ('pro_info', models.CharField(max_length=300, verbose_name='项目简单介绍')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('is_run', models.BooleanField(default=False)),
            ],
        ),
    ]
