# Generated by Django 2.0.7 on 2018-07-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qihuan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Download',
            new_name='DevelopProject',
        ),
        migrations.AlterModelOptions(
            name='developproject',
            options={'ordering': ['-create_time']},
        ),
    ]
