# Generated by Django 2.0.7 on 2018-07-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qihuan', '0003_developproject_pro_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='developproject',
            name='pro_small',
            field=models.ImageField(default=0, upload_to='project_img', verbose_name='项目小图标'),
        ),
    ]
