# Generated by Django 2.0.7 on 2018-07-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qihuan', '0004_developproject_pro_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developproject',
            name='is_run',
            field=models.BooleanField(default=False, verbose_name='是部署?'),
        ),
        migrations.AlterField(
            model_name='developproject',
            name='pro_cate',
            field=models.CharField(choices=[('web', 'web'), ('人工智能', '人工智能'), ('爬虫', '爬虫')], max_length=20, verbose_name='项目类型'),
        ),
    ]
