# Generated by Django 2.0.7 on 2018-07-07 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='python', max_length=30, verbose_name='类型名')),
            ],
            options={
                'verbose_name': '类型表',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签表',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('summary', models.CharField(max_length=50, verbose_name='摘要')),
                ('body', models.TextField(verbose_name='正文')),
                ('author', models.CharField(max_length=15, verbose_name='作者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创作时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cate_name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='文章类型')),
                ('marks_name', models.ManyToManyField(to='blog.Mark', verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章信息表',
                'ordering': ['-modify_time', 'title'],
            },
        ),
    ]
