# Generated by Django 2.0.7 on 2018-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('summary', models.CharField(max_length=50, verbose_name='摘要')),
                ('body', models.TextField(verbose_name='正文')),
                ('author', models.CharField(max_length=15, verbose_name='作者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创作时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '文章信息表',
            },
        ),
    ]
