# Generated by Django 2.0.7 on 2018-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_number',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='post',
            name='read_number',
            field=models.IntegerField(default=0, verbose_name='阅读数量'),
        ),
    ]
