# Generated by Django 2.0.7 on 2018-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180709_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default=0, upload_to='', verbose_name='文章封面图片'),
        ),
    ]
