# Generated by Django 2.0.7 on 2018-07-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default=0, upload_to='article_index', verbose_name='文章封面图片'),
        ),
    ]
