# Generated by Django 2.0.7 on 2018-07-07 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('text', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('up_common', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Common')),
            ],
            options={
                'verbose_name': '评论详情表',
                'ordering': ['-create_time', 'up_common'],
            },
        ),
    ]
