# Generated by Django 2.0.7 on 2018-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180707_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='postflag',
            field=models.BooleanField(default=False),
        ),
    ]
