# Generated by Django 2.0.7 on 2018-07-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_common_postflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common',
            name='postflag',
        ),
        migrations.AlterField(
            model_name='common',
            name='up_common',
            field=models.IntegerField(default=0),
        ),
    ]
