# Generated by Django 2.0.7 on 2018-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20180709_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='like_number',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='common',
            name='read_number',
            field=models.IntegerField(default=0, verbose_name='阅读数量'),
        ),
    ]
