# Generated by Django 2.0.7 on 2018-07-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20180709_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common',
            name='like_number',
        ),
        migrations.RemoveField(
            model_name='common',
            name='read_number',
        ),
    ]
