import unittest
from test_html_template.HTMLTestRunner import HTMLTestRunner
from blog_test.test_post_model import PostTestCase

if __name__ == '__main__':
	#创建TestSuite对象
	suite = unittest.TestSuite()
	#添加我们的测试类到suite对象中
	suite.addTests(unittest.TestLoader().loadTestsFromTestCase(PostTestCase))
	#运行测试,输出到测试文档中
	with open('Test_Post_Report.html','w') as f:
		runner = HTMLTestRunner(stream=f,
								title='Blog Post Test Tepost',
								description='generated by HTMLTestRunner.',
								verbosity=2
								)
		runner.run(suite)